#测试环境

spring:
  #缓存
  cache:
    type: redis
  data:
    #mongodb config
    mongodb:
      database: test
      uri: mongodb://120.24.241.113:27017
  #mysql config
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yuechi_hospital?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&&useSSL=true
    username: root
    password: 123
  #redis config
  redis:
    database: 1
    host: sevencai.cn
    jedis:
      pool:
        max-active: 800
        max-idle: 20
        max-wait: 10000ms
        min-idle: 2
    password: qicai999
    port: 6379
    timeout: 30000ms
  #文件上传控制
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

#日志级别
logging:
  level:
    com:
      austin: DEBUG

#自定义属性
file:
  pre-visit-url: D:/upload
  upload-folder: D:/upload
